name: Build and deploy @eduardoroth/media-player

on:
  push:
    branches:
      - main
      - 'v**'

jobs:
  build-publish:
    name: Build and publish media-player
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5.0.0
        name: Checkout code

      - uses: EndBug/version-check@v2
        name: Check if there's an update on package version
        id: check
        with:
          diff-search: true

      - uses: actions/setup-node@v5.0.0
        name: Setup NodeJS
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - run: npm ci
        name: Install dependencies

      - run: npm run build
        name: Build project

      - if: steps.check.outputs.changed == 'true'
        name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
