name: Publish media-player to npm

on:
  push:
    branches:
      - main
      - 'v**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: EndBug/version-check@v2
        id: check
        with:
          diff-search: true

      - if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - if: steps.check.outputs.changed == 'true'
        run: npm ci

      - if: steps.check.outputs.changed == 'true'
        run: npm run build

      - if: steps.check.outputs.changed == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - if: steps.check.outputs.changed == 'true'
        run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}